##===- projects/thrud/lib/Makefile -------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

DIRS = Support DivergenceAnalysis
PARALLEL_DIRS = FeatureExtraction ThreadCoarsening

include $(LEVEL)/Makefile.common
