##===- lib/Analysis/Makefile -------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../

LIBRARYNAME=libDivergenceAnalysis
LOADABLE_MODULE = 1

USEDLIBS = thrudSupport.a 

include $(LEVEL)/Makefile.common
