##===- lib/Analysis/Makefile -------------------------------*- Makefile -*-===##
#
#                     The LLVM Compiler Infrastructure
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
##===----------------------------------------------------------------------===##

LEVEL = ../../

LIBRARYNAME = LLVMTC
LOADABLE_MODULE = 1

USEDLIB = thrudSupport.a

LIBS += -ldivergence_analysis

include $(LEVEL)/Makefile.common
